services:
  app:
    build:
      context: src
      dockerfile: Starter.Template.AOT.Api/Dockerfile
      args:
        EXTRA_CA_CERT: ${EXTRA_CA_CERT:-}
    ports:
      - "8080:8080"
    depends_on:
      - datadog-agent
    labels:
      com.datadoghq.ad.logs: '[{"source": "dotnet", "service": "starter-template-aot-api"}]'

  datadog-agent:
    image: registry.datadoghq.com/agent:7
    container_name: dd-agent
    entrypoint: >
      /bin/bash -c "
        cat /custom-certs/proxy-ca.crt >> /etc/ssl/certs/cacert.pem &&
        exec /bin/entrypoint.sh
      "
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=datadoghq.com
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_ENV=${DD_ENV:-local}
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_HOSTNAME=starter-template-aot-local
      - DD_CONVERT_DD_SITE_FQDN_ENABLED=false
      - DD_SYSTEM_PROBE_ENABLED=false
      - DD_PROCESS_AGENT_ENABLED=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /usr/local/share/ca-certificates/swp-ca-production.crt:/custom-certs/proxy-ca.crt:ro
